routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('home', 'HomeController@index')->name('home');
Route::get('phpinfo', function () {
    phpinfo();
});

Auth::routes();

Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Route::get('/{link}', 'HomeController@detail');
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('category', 'CategoryController');
    Route::get('book/select', 'BookController@select');
    Route::resource('book', 'BookController');
    Route::get('order/member', 'OrderController@member')->name('order.member');
    Route::put('order/status', 'OrderController@status')->name('order.status');
    Route::get('order/summary', 'OrderController@summary')->name('order.summary');
    Route::resource('order', 'OrderController');
    Route::resource('catalog', 'CatalogController');
    Route::resource('ads', 'AdsController');
    Route::resource('event', 'EventController');
    Route::resource('news', 'NewsController');
    Route::resource('promo', 'PromoController');
    Route::resource('author', 'AuthorController');
    Route::resource('slider', 'SliderController');
    Route::resource('report', 'ReportController');
    Route::get('member/order', 'MemberController@transactions')->name('member.order');
    Route::resource('member', 'MemberController');
    Route::resource('user', 'UserController');
    Route::post('logout', '\App\Http\Controllers\Auth\AdminLoginController@logout')->name('logout');
});

Route::get('admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Auth\AdminLoginController@login')->name('admin.login');
Route::get('admin/register', 'Auth\AdminLoginController@showRegisterPage')->name('admin.register');
Route::post('admin/register', 'Auth\AdminLoginController@register')->name('admin.register');

// frontend
Route::get('register', 'Auth\RegisterController@showRegisterForm')->name('register');
Route::get('member', 'HomeController@member')->name('member');
Route::post('search', 'HomeController@search')->name('search');
Route::get('get-city/{id}', 'HomeController@getCity')->name('get-city');
Route::get('get-district/{id}', 'HomeController@getDistrict')->name('get-district');
Route::get('cart', 'HomeController@cart')->name('cart');
Route::get('book/{id}', 'HomeController@book')->name('book');
Route::get('detail/{link}', 'HomeController@detail')->name('detail');
Route::get('checkout', 'HomeController@checkout')->name('checkout');
Route::post('checkout', 'HomeController@saveCheckout')->name('checkout');
Route::get('courier-check', 'HomeController@courierCheck')->name('courier-check');
Route::post('summary', 'HomeController@summary')->name('summary');
Route::get('catalog', 'HomeController@catalog')->name('catalog');
Route::get('events', 'HomeController@event')->name('events');
Route::get('event/{link}', 'HomeController@eventDetail')->name('event');
Route::get('promo/{link}', 'HomeController@promo')->name('promo');
Route::get('news-all', 'HomeController@news')->name('news-all');
Route::get('news/{link}', 'HomeController@showNews')->name('news');
Route::get('category/{link}', 'HomeController@category')->name('category');
Route::get('about-us', 'HomeController@aboutUs')->name('about-us');
Route::get('send-document', 'HomeController@sendDocument')->name('send-document');
Route::get('send-ilustrator', 'HomeController@sendIlustrator')->name('send-ilustrator');
Route::post('save-document', 'HomeController@saveDocument')->name('save-document');
Route::post('save-address', 'UserController@saveAddress')->name('save-address');
Route::post('edit-profile', 'UserController@editProfile')->name('edit-profile');
Route::get('call-us', 'HomeController@callUs')->name('call-us');
Route::post('message', 'HomeController@message')->name('message');
Route::get('wishlist', 'HomeController@wishlist')->name('wishlist');
Route::post('wishlist', 'HomeController@setWishlist')->name('wishlist');
Route::post('delete-wishlist', 'HomeController@deleteWishlist')->name('delete-wishlist');
Route::get('reseller', 'HomeController@reseller')->name('reseller');
Route::get('credit', 'HomeController@credit')->name('credit');
Route::get('testimonial', 'HomeController@testimonial')->name('testimonial');
Route::get('forgot-password', 'HomeController@forgotPassword')->name('forgot-password');
Route::post('send-forgot-password', 'HomeController@sendForgotPassword')->name('send-forgot-password');
Route::get('cara-belanja', 'HomeController@caraBelanja')->name('cara-belanja');
Route::get('pembayaran', 'HomeController@pembayaran')->name('pembayaran');
Route::get('pengiriman', 'HomeController@pengiriman')->name('pengiriman');

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    protected $fillable = [
        'name',
        'biography',
        'phone',
        'email',
        'whatsapp'
    ];
}

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Author;

class AuthorController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = Author::all();

        return view('admin.author.index', compact('model'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.author.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $model = Author::create($request->all());

        return redirect()->route('admin.author.index')->with('success', 'Data Author berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Author::find($id);

        return view('admin.author.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Author::find($id);
        $model->name = $request->input('name');
        $model->biography = $request->input('biography');
        $model->save();

        return redirect()->route('admin.author.index')->with('success', 'Data Author berhasil diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Author::find($id);

        if ($model->delete())
            return response()->json([
                'success' => true,
                'message' => 'Data penulis berhasil dihapus',
            ]);
        else
            return response()->json([
                'success' => false,
                'message' => 'Data penulis tidak berhasil dihapus',
            ]);
    }
}

resources/views/admin/author/create.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-xl-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Tambah Penulis
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form class="m-form" method="POST" action="{{ route('admin.author.store') }}">
                        @csrf
                        <div class="m-portlet__body">
                            <div class="m-form__section m-form__section--first">
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Nama Penulis
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control m-input" name="name" placeholder="Masukkan Nama Penulis" required>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Ringkasan
                                    </label>
                                    <div class="col-lg-6">
                                        <textarea class="form-control m-input" id="biography" name="biography" placeholder="Masukkan Biografi Penulis" style="height: 100px"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions--solid">
                                <div class="row">
                                    <div class="col-lg-2"></div>
                                    <div class="col-lg-6">
                                        <button type="submit" class="btn btn-success" id="m_sweetalert_demo_3_3">
                                            Simpan
                                        </button>
                                        <button type="reset" class="btn btn-secondary">
                                            Batal
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
</div>
@endsection

@section('scripts')
<script>
    const bio = document.getElementById("biography")
    CKEDITOR.replace(bio);

    CKEDITOR.config.allowedContent = true;
</script>
@endsection

resources/views/admin/author/edit.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-xl-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Edit Penulis
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form class="m-form" method="post" action="{{ route('admin.author.update', $model->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="m-portlet__body">
                            <div class="m-form__section m-form__section--first">
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Nama Penulis
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control m-input" name="name" value="{{ old('name', $model->name) }}" placeholder="Masukkan Nama Penulis" required>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Biografi
                                    </label>
                                    <div class="col-lg-6">
                                        <textarea class="form-control m-input" id="biography" name="biography" placeholder="Masukkan Biografi Penulis" style="height: 100px">{{ old('biography', $model->biography) }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions--solid">
                                <div class="row">
                                    <div class="col-lg-2"></div>
                                    <div class="col-lg-6">
                                        <button type="submit" class="btn btn-success" id="m_sweetalert_demo_3_3">
                                            Simpan
                                        </button>
                                        <button type="reset" class="btn btn-secondary">
                                            Batal
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
</div>
@endsection

@section('scripts')
<script>
    const bio = document.getElementById("biography")
    CKEDITOR.replace(bio);

    CKEDITOR.config.allowedContent = true;
</script>
@endsection

resources/views/admin/author/index.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Daftar Penulis
                                </h3>
                            </div>
                        </div>
                    </div>

                    <div class="m-portlet__body">
                        <!--begin::Section-->
                        <div class="m-section">
                            <div class="m-section__content">
                                @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert"></button> 
                                    <strong>{{ $message }}</strong>
                                </div>
                                @endif
                                @if ($message = Session::get('error'))
                                <div class="alert alert-danger alert-block">
                                    <button type="button" class="close" data-dismiss="alert"></button> 
                                    <strong>{{ $message }}</strong>
                                </div>
                                @endif
                                <table class="table m-table m-table--head-bg-success table-hover" style="font-size:12px;">
                                    <thead>
                                        <tr>
                                            <th>&nbsp;&nbsp;No.</th>
                                            <th>Nama</th>
                                            <th>Edit</th>
                                            <th>Hapus</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php $inc = 1 @endphp
                                        @foreach ($model as $row)
                                        <tr>
                                            <th scope="row">&nbsp;&nbsp;&nbsp;&nbsp;{{ sprintf('%03d', $inc) }}</th>
                                            <td>{{ $row->name }}</td>
                                            <td>
                                                <a href="{{ route('admin.author.edit', $row->id) }}">
                                                    <span> <i class="fa flaticon-edit-1"></i> <span>
                                                </a>
                                            </td>
                                            <td>
                                                <a class="remove" data-id="{{ $row->id }}" href="javascript:;">
                                                    <span> <i class="fa flaticon-delete-2"></i> </span>
                                                </a>
                                            </td>
                                        </tr>
                                            @php $inc++ @endphp
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!--end::Section-->
                    </div>
                </div>
                <!--end::Portlet-->
            </div>
            <!--End::Section-->
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $('.table').DataTable({
        dom: 'Bfrtip',
    });

    $(document).on('click', '.remove', function (e) {
        e.preventDefault()

        if (confirm('Apakah kamu yakin akan menghapus data ini?') == true) {
            const id = $(this).data('id')
            
            $.ajax({
                method: 'delete',
                url: '{{ route('admin.author.destroy', $row->id) }}',
                data: {
                    _token: '{{ csrf_token() }}',
                    id: id
                },
                cache: false,
                success: function (result) {
                    if (result.success == true) {
                        location.href = '{{ route('admin.author.index') }}'
                    }
                }
            })
        }
    })
</script>
@endsection