routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('home', 'HomeController@index')->name('home');
Route::get('phpinfo', function () {
    phpinfo();
});

Auth::routes();

Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Route::get('/{link}', 'HomeController@detail');
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('category', 'CategoryController');
    Route::get('book/select', 'BookController@select');
    Route::resource('book', 'BookController');
    Route::get('order/member', 'OrderController@member')->name('order.member');
    Route::put('order/status', 'OrderController@status')->name('order.status');
    Route::get('order/summary', 'OrderController@summary')->name('order.summary');
    Route::resource('order', 'OrderController');
    Route::resource('catalog', 'CatalogController');
    Route::resource('ads', 'AdsController');
    Route::resource('event', 'EventController');
    Route::resource('news', 'NewsController');
    Route::resource('promo', 'PromoController');
    Route::resource('author', 'AuthorController');
    Route::resource('slider', 'SliderController');
    Route::resource('report', 'ReportController');
    Route::get('member/order', 'MemberController@transactions')->name('member.order');
    Route::resource('member', 'MemberController');
    Route::resource('user', 'UserController');
    Route::post('logout', '\App\Http\Controllers\Auth\AdminLoginController@logout')->name('logout');
});

Route::get('admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Auth\AdminLoginController@login')->name('admin.login');
Route::get('admin/register', 'Auth\AdminLoginController@showRegisterPage')->name('admin.register');
Route::post('admin/register', 'Auth\AdminLoginController@register')->name('admin.register');

// frontend
Route::get('register', 'Auth\RegisterController@showRegisterForm')->name('register');
Route::get('member', 'HomeController@member')->name('member');
Route::post('search', 'HomeController@search')->name('search');
Route::get('get-city/{id}', 'HomeController@getCity')->name('get-city');
Route::get('get-district/{id}', 'HomeController@getDistrict')->name('get-district');
Route::get('cart', 'HomeController@cart')->name('cart');
Route::get('book/{id}', 'HomeController@book')->name('book');
Route::get('detail/{link}', 'HomeController@detail')->name('detail');
Route::get('checkout', 'HomeController@checkout')->name('checkout');
Route::post('checkout', 'HomeController@saveCheckout')->name('checkout');
Route::get('courier-check', 'HomeController@courierCheck')->name('courier-check');
Route::post('summary', 'HomeController@summary')->name('summary');
Route::get('catalog', 'HomeController@catalog')->name('catalog');
Route::get('events', 'HomeController@event')->name('events');
Route::get('event/{link}', 'HomeController@eventDetail')->name('event');
Route::get('promo/{link}', 'HomeController@promo')->name('promo');
Route::get('news-all', 'HomeController@news')->name('news-all');
Route::get('news/{link}', 'HomeController@showNews')->name('news');
Route::get('category/{link}', 'HomeController@category')->name('category');
Route::get('about-us', 'HomeController@aboutUs')->name('about-us');
Route::get('send-document', 'HomeController@sendDocument')->name('send-document');
Route::get('send-ilustrator', 'HomeController@sendIlustrator')->name('send-ilustrator');
Route::post('save-document', 'HomeController@saveDocument')->name('save-document');
Route::post('save-address', 'UserController@saveAddress')->name('save-address');
Route::post('edit-profile', 'UserController@editProfile')->name('edit-profile');
Route::get('call-us', 'HomeController@callUs')->name('call-us');
Route::post('message', 'HomeController@message')->name('message');
Route::get('wishlist', 'HomeController@wishlist')->name('wishlist');
Route::post('wishlist', 'HomeController@setWishlist')->name('wishlist');
Route::post('delete-wishlist', 'HomeController@deleteWishlist')->name('delete-wishlist');
Route::get('reseller', 'HomeController@reseller')->name('reseller');
Route::get('credit', 'HomeController@credit')->name('credit');
Route::get('testimonial', 'HomeController@testimonial')->name('testimonial');
Route::get('forgot-password', 'HomeController@forgotPassword')->name('forgot-password');
Route::post('send-forgot-password', 'HomeController@sendForgotPassword')->name('send-forgot-password');
Route::get('cara-belanja', 'HomeController@caraBelanja')->name('cara-belanja');
Route::get('pembayaran', 'HomeController@pembayaran')->name('pembayaran');
Route::get('pengiriman', 'HomeController@pengiriman')->name('pengiriman');

app/Models/Promo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Promo extends Model
{
    protected $fillable = [
        'title',
        'start_date',
        'end_date',
        'percentage',
        'fix_price',
        'status'
    ];

    public function products ()
    {
        return $this->hasMany(PromoProduct::class, 'promo_id', 'id')->orderBy('created_at', 'desc');
    }
}

app/Http/Controllers/Admin/PromoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

use App\Models\Promo;
use App\Models\PromoProduct;
use App\Models\Book;

class PromoController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = Promo::all();

        return view('admin.promo.index', compact('model'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.promo.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $model = new Promo;
        $model->title = $request->input('title');
        $model->link = Str::slug($request->input('title'), '-');
        $model->start_date = $request->input('start_date');
        $model->end_date = $request->input('end_date');
        $model->status = $request->input('status');
        $model->save();

        return redirect()->route('admin.promo.index')->with('success', 'Data iklan berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Promo::find($id);

        return view('admin.promo.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Promo::find($id);
        $books = Book::all();

        $data = [];
        foreach ($books as $row) {
            array_push($data, [
                'id' => $row->id,
                'title' => $row->title,
                'discount' => $row->discount
            ]);
        }

        return view('admin.promo.edit', compact('model', 'data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \DB::beginTransaction();

        try {
            // save detail
            $promo = PromoProduct::where('promo_id', (int) $id);
            if ($promo->count()) {
                foreach ($promo->get() as $row) {
                    $book = Book::find($row->product_id);
                    $book->discount = 20;
                    $book->save();
                }

                $promo->delete();
            }

            if ($request->input('books')) {
                foreach ($request->input('books') as $key => $row) {
                    $detail = new PromoProduct;
                    $detail->promo_id = (int) $id;
                    $detail->product_id = (int) $row;
                    $detail->save();
    
                    $discountEdit = Book::find((int) $row);
                    $discountEdit->discount = $request->input('discount')[$key] ?? 0;
                    $discountEdit->save();
                }
            }

            $model = Promo::find($id);
            $model->start_date = $request->input('start_date');
            $model->end_date = $request->input('end_date');
            $model->status = $request->input('status');
            $model->save();

            \DB::commit();
        } catch (Exception $e) {
            \DB::rollBack();
            dd($e);
        }

        return redirect()->route('admin.promo.index')->with('success', 'Data iklan berhasil diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Promo::find($id);

        if ($model->delete())
            return response()->json([
                'success' => true,
                'message' => 'Data promo berhasil dihapus',
            ]);
        else
            return response()->json([
                'success' => false,
                'message' => 'Data promo tidak berhasil dihapus',
            ]);

    }
}

resources/views/admin/promo/create.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-xl-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Tambah Promo
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form class="m-form" method="POST" action="{{ route('admin.promo.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="m-portlet__body">
                            <div class="m-form__section m-form__section--first">
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Judul Promo
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control m-input" name="title" placeholder="Masukkan Judul Promo" required>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Start Date
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="date" class="form-control m-input" name="start_date" placeholder="YYYY-MM-DD">
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Expired
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="date" class="form-control m-input" name="end_date" placeholder="YYYY-MM-DD">
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Status
                                    </label>
                                    <div class="col-lg-6">
                                        <div class="m-radio-inline">
                                            <label class="m-radio">
                                                <input type="radio" name="status" value="1">
                                                Aktif
                                                <span></span>
                                            </label>
                                            <label class="m-radio">
                                                <input type="radio" name="status" value="0">
                                                Tidak Aktif
                                                <span></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions--solid">
                                <div class="row">
                                    <div class="col-lg-2"></div>
                                    <div class="col-lg-6">
                                        <button type="submit" class="btn btn-success" id="m_sweetalert_demo_3_3">
                                            Simpan
                                        </button>
                                        <button type="reset" class="btn btn-secondary">
                                            Batal
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
</div>
@endsection

resources/views/admin/promo/edit.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-xl-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Edit Promo
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form class="m-form" method="post" action="{{ isset($model) ? route('admin.promo.update', $model->id) : route('admin.promo.store') }}" enctype="multipart/form-data">
                        @csrf
                        @if (isset($model))
                        @method('PUT')
                        <input type="hidden" name="id" value="{{ $model->id }}">
                        @endif
                        <div class="m-portlet__body">
                            <div class="m-form__section m-form__section--first">
                                @if (isset($model))
                                @else
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Tipe
                                    </label>
                                    <div class="col-lg-6">
                                        <select class="form-control m-input" name="title">
                                            <option value="flash sale">FLASH SALE</option>
                                            <option value="promo bulan ini">PROMO BULAN INI</option>
                                            <option value="buku baru">BUKU BARU</option>
                                            <option value="best sellers">BEST SELLERS</option>
                                            <option value="buku anak">BUKU ANAK</option>
                                        </select>
                                    </div>
                                </div>
                                @endif
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Tanggal Mulai
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control datepicker m-input" name="start_date" value="{{ old('start_date', isset($model->start_date) ? $model->start_date : date('Y-m-d')) }}" placeholder="Masukkan Start Date">
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Tanggal Berakhir
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control datepicker m-input" name="end_date" value="{{ old('end_date', isset($model->end_date) ? $model->end_date : date('Y-m-d')) }}" placeholder="Masukkan Expired Promo">
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Publish
                                    </label>
                                    <div class="col-lg-6">
                                        <label class="radio-inline">
                                            <input type="radio" class="form-control m-input" name="status" value="0" {{ isset($model->status) && $model->status == 0 ? 'checked' : '' }}>
                                            Tidak Aktif
                                        </label>
                                        <label class="radio-inline">
                                            <input type="radio" class="form-control m-input" name="status" value="1" {{ isset($model->status) && $model->status == 1 ? 'checked' : '' }}>
                                            Aktif
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <div class="col-lg-9">
                                        <button id="add_book" class="form-control btn btn-primary">Tambah Buku</button>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <div class="col-lg-9">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th style="width: 50%">Judul Buku</th>
                                                    <th style="width: 30%">Diskon (%)</th>
                                                    <th style="width: 20%">Aksi</th>
                                                </tr>
                                            </thead>
                                            <tbody id="book_items">
                                                @if (isset($model->products))
                                                    @foreach ($model->products as $row)
                                                    <tr>
                                                        <td style="width: 50%">
                                                            <select name="books[]" class="book">
                                                                @foreach ($data as $key => $val)
                                                                <option value="{{ $val['id'] }}" {{ $row->product['id'] == $val['id'] ? 'selected' : '' }}>{{ $val['title'] }}</option>
                                                                @endforeach
                                                            </select>
                                                        </td>
                                                        <td style="width: 30%"><input class="form-control m-input" type="number" name="discount[]" value="{{ $row->product['discount'] }}" class="discount"></td>
                                                        <td style="width: 20%"><button class="btn btn-primary btn-xs remove"><i class="fa flaticon-delete-2"></i> Hapus</button></td>
                                                    </tr>
                                                    @endforeach
                                                @endif
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions--solid">
                                <div class="row">
                                    <div class="col-lg-2"></div>
                                    <div class="col-lg-6">
                                        <button type="submit" class="btn btn-success" id="m_sweetalert_demo_3_3">
                                            Simpan
                                        </button>
                                        <button type="reset" class="btn btn-secondary">
                                            Batal
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
</div>
@endsection

@section('scripts')
<script>
    const base_url = '{{ url('/') }}'

    $('.datepicker').datepicker({
        format: 'yyyy-mm-dd'
    })

    $('select').select2()

    let index = 1
    $('#add_book').on('click', function (e) {
        e.preventDefault()

        let html = `
            <tr>
                <td><select name="books[]" id="book_${index}" class="book"></select></td>
                <td><input type="number" name="discount[]" id="discount_${index}" class="discount"></td>
                <td><button class="btn btn-danger btn-xs remove">Hapus</button></td>
            </tr>
        `

        $('#book_items').append(html)

        loadBooks(index)
        index++
    })

    const loadBooks = function (i) {
        $book_id = $('#book_' + i)

        $.get(base_url + '/admin/book/select', function (data) {
            for (var i = 0; i < data.length; i++) {
                $book_id.append('<option value=' + data[i].id + '>' + data[i].title +' </option>');
            }
            $book_id.change();
        })
    }

    $(document).on('click', '.remove', function (e) {
        e.preventDefault()

        index--
        $(this).parent().parent().remove()
    })
</script>
@endsection

resources/views/admin/promo/index.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Daftar Promo
                                </h3>
                            </div>
                        </div>
                    </div>

                    <div class="m-portlet__body">
                        <!--begin::Section-->
                        <div class="m-section">
                            <div class="m-section__content">
                                @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert"></button> 
                                    <strong>{{ $message }}</strong>
                                </div>
                                @endif
                                @if ($message = Session::get('error'))
                                <div class="alert alert-danger alert-block">
                                    <button type="button" class="close" data-dismiss="alert"></button> 
                                    <strong>{{ $message }}</strong>
                                </div>
                                @endif
                                <table class="table m-table m-table--head-bg-success table-hover" style="font-size:12px;">
                                    <thead>
                                        <tr>
                                            <th>&nbsp;&nbsp;No.</th>
                                            <th>Judul</th>
                                            <th>Link</th>
                                            <th>Start Date</th>
                                            <th>Expired</th>
                                            <th>Status</th>
                                            <th>Edit</th>
                                            <!--<th>Hapus</th>-->
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php $inc = 1 @endphp
                                        @foreach ($model as $row)
                                        <tr>
                                            <th scope="row">&nbsp;&nbsp;&nbsp;&nbsp;{{ sprintf('%03d', $inc) }}</th>
                                            <td>{{ $row->title }}</td>
                                            <td>{{ $row->link }}</td>
                                            <td>{{ $row->start_date }}</td>
                                            <td>{{ $row->end_date }}</td>
                                            <td>{{ $row->status == 1 ? 'Active' : 'Inactive' }}</td>
                                            <td align="center">
                                                <a href="{{ route('admin.promo.edit', $row->id) }}">
                                                    <span> <i class="fa flaticon-edit-1"></i> <span>
                                                </a>
                                            </td>
                                            <!--<td align="center">-->
                                            <!--    <a href="{{ route('admin.promo.destroy', $row->id) }}" class="delete" method="delete">-->
                                            <!--        <span> <i class="fa flaticon-delete-2"></i> </span>-->
                                            <!--    </a>-->
                                            <!--</td>-->
                                        </tr>
                                            @php $inc++ @endphp
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!--end::Section-->
                    </div>
                </div>
                <!--end::Portlet-->
            </div>
            <!--End::Section-->
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $('.table').DataTable({
        dom: 'Bfrtip',
    });
    
    // $(document).on('click', '.delete', function (e) {
    //     e.preventDefault()
        
    //     const c = confirm('Anda yakin mau menghapus data ini?')
    //     if (c == true) {
    //         $.ajax({
    //             method: 'delete',
    //             url: $(this).attr('href'),
    //             data: {
    //                 '_token': '{{ csrf_token() }}',
    //             },
    //             cache: false,
    //             success: function (result) {
    //                 if (result.success == true)
    //                     location.href = '{{ route('admin.promo.index') }}'
    //             }
    //         })
    //     }
    // })
</script>
@endsection