routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('home', 'HomeController@index')->name('home');
Route::get('phpinfo', function () {
    phpinfo();
});

Auth::routes();

Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Route::get('/{link}', 'HomeController@detail');
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('category', 'CategoryController');
    Route::get('book/select', 'BookController@select');
    Route::resource('book', 'BookController');
    Route::get('order/member', 'OrderController@member')->name('order.member');
    Route::put('order/status', 'OrderController@status')->name('order.status');
    Route::get('order/summary', 'OrderController@summary')->name('order.summary');
    Route::resource('order', 'OrderController');
    Route::resource('catalog', 'CatalogController');
    Route::resource('ads', 'AdsController');
    Route::resource('event', 'EventController');
    Route::resource('news', 'NewsController');
    Route::resource('promo', 'PromoController');
    Route::resource('author', 'AuthorController');
    Route::resource('slider', 'SliderController');
    Route::resource('report', 'ReportController');
    Route::get('member/order', 'MemberController@transactions')->name('member.order');
    Route::resource('member', 'MemberController');
    Route::resource('user', 'UserController');
    Route::post('logout', '\App\Http\Controllers\Auth\AdminLoginController@logout')->name('logout');
});

Route::get('admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Auth\AdminLoginController@login')->name('admin.login');
Route::get('admin/register', 'Auth\AdminLoginController@showRegisterPage')->name('admin.register');
Route::post('admin/register', 'Auth\AdminLoginController@register')->name('admin.register');

// frontend
Route::get('register', 'Auth\RegisterController@showRegisterForm')->name('register');
Route::get('member', 'HomeController@member')->name('member');
Route::post('search', 'HomeController@search')->name('search');
Route::get('get-city/{id}', 'HomeController@getCity')->name('get-city');
Route::get('get-district/{id}', 'HomeController@getDistrict')->name('get-district');
Route::get('cart', 'HomeController@cart')->name('cart');
Route::get('book/{id}', 'HomeController@book')->name('book');
Route::get('detail/{link}', 'HomeController@detail')->name('detail');
Route::get('checkout', 'HomeController@checkout')->name('checkout');
Route::post('checkout', 'HomeController@saveCheckout')->name('checkout');
Route::get('courier-check', 'HomeController@courierCheck')->name('courier-check');
Route::post('summary', 'HomeController@summary')->name('summary');
Route::get('catalog', 'HomeController@catalog')->name('catalog');
Route::get('events', 'HomeController@event')->name('events');
Route::get('event/{link}', 'HomeController@eventDetail')->name('event');
Route::get('promo/{link}', 'HomeController@promo')->name('promo');
Route::get('news-all', 'HomeController@news')->name('news-all');
Route::get('news/{link}', 'HomeController@showNews')->name('news');
Route::get('category/{link}', 'HomeController@category')->name('category');
Route::get('about-us', 'HomeController@aboutUs')->name('about-us');
Route::get('send-document', 'HomeController@sendDocument')->name('send-document');
Route::get('send-ilustrator', 'HomeController@sendIlustrator')->name('send-ilustrator');
Route::post('save-document', 'HomeController@saveDocument')->name('save-document');
Route::post('save-address', 'UserController@saveAddress')->name('save-address');
Route::post('edit-profile', 'UserController@editProfile')->name('edit-profile');
Route::get('call-us', 'HomeController@callUs')->name('call-us');
Route::post('message', 'HomeController@message')->name('message');
Route::get('wishlist', 'HomeController@wishlist')->name('wishlist');
Route::post('wishlist', 'HomeController@setWishlist')->name('wishlist');
Route::post('delete-wishlist', 'HomeController@deleteWishlist')->name('delete-wishlist');
Route::get('reseller', 'HomeController@reseller')->name('reseller');
Route::get('credit', 'HomeController@credit')->name('credit');
Route::get('testimonial', 'HomeController@testimonial')->name('testimonial');
Route::get('forgot-password', 'HomeController@forgotPassword')->name('forgot-password');
Route::post('send-forgot-password', 'HomeController@sendForgotPassword')->name('send-forgot-password');
Route::get('cara-belanja', 'HomeController@caraBelanja')->name('cara-belanja');
Route::get('pembayaran', 'HomeController@pembayaran')->name('pembayaran');
Route::get('pengiriman', 'HomeController@pengiriman')->name('pengiriman');

app/Models/Catalog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Catalog extends Model
{
    protected $fillable = [
        'title',
        'sub_title',
        'link',
        'image_url',
        'download_url',
        'status',
    ];
}

app/Http/Controllers/Admin/CatalogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

use App\Models\Catalog;

class CatalogController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = Catalog::all();

        return view('admin.catalog.index', compact('model'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.catalog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        ini_set('upload_max_filesize', '24M');
        ini_set('post_max_size', '24M');
        ini_set('max_input_time', 1024);
        ini_set('max_execution_time', 1024);

        $filename = '';
        if ($request->file('image_url')) {
            $path = 'uploads/';
            $file = $request->file('image_url');
            
            $filename = \pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);
            $filename = 'catalog_' . Str::slug($filename, '-');
            $filename .= '.' . $extension;
    
            $file->move($path, $filename);
        }

        $download_filename = '';
        if ($request->file('download_url')) {
            $path = 'uploads/';
            $file = $request->file('download_url');
            
            $download_filename = \pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);
            $download_filename = 'catalog_' . Str::slug($download_filename, '-');
            $download_filename .= '.' . $extension;
    
            $file->move($path, $download_filename);
        }

        $model = new Catalog;
        $model->user_id = 1;
        $model->title = $request->input('title');
        $model->sub_title = $request->input('sub_title');
        $model->link = Str::slug($request->input('title'), '-');
        $model->image_url = $filename;
        $model->download_url = $download_filename;
        $model->save();

        return redirect()->route('admin.catalog.index')->with('success', 'Data iklan berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Catalog::find($id);

        return view('admin.catalog.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $filename = $request->input('is_image');
        $download_filename = $request->input('is_download');

        if ($request->file('image_url')) {
            $path = 'uploads/';
            $file = $request->file('image_url');
            
            $filename = \pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);
            $filename = 'catalog_' . Str::slug($filename, '-');
            $filename .= '.' . $extension;
    
            $file->move($path, $filename);
        }

        if ($request->file('download_url')) {
            $path = 'uploads/';
            $file = $request->file('download_url');

            $download_filename = \pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $extension = pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION);
            $download_filename = 'catalog_' . Str::slug($download_filename, '-');
            $download_filename .= '.' . $extension;
    
            $file->move($path, $download_filename);
        }

        $model = Catalog::find($id);
        $model->title = $request->input('title');
        $model->link = Str::slug($request->input('title'), '-');
        $model->sub_title = $request->input('sub_title');
        $model->image_url = $filename;
        $model->download_url = $download_filename;
        $model->save();

        return redirect()->route('admin.catalog.index')->with('success', 'Data iklan berhasil diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Catalog::find($id);

        if ($model->delete())
            return response()->json([
                'success' => true,
                'message' => 'Data iklan berhasil dihapus',
            ]);
        else
            return response()->json([
                'success' => false,
                'message' => 'Data iklan tidak berhasil dihapus',
            ]);
    }
}

resources/views/admin/catalog/create.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-xl-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Tambah Katalog
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form class="m-form" method="POST" action="{{ route('admin.catalog.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="m-portlet__body">
                            <div class="m-form__section m-form__section--first">
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Judul Katalog
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control m-input" name="title" placeholder="Masukkan Judul Katalog" required>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Sub Judul Katalog
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control m-input" name="sub_title" placeholder="Masukkan Sub Judul Katalog" required>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Upload Image
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="file" id="image_url" class="form-control m-input" name="image_url" placeholder="Upload Gambar Buku" accept=".jpg, .jpeg, .png, image/jpeg, image/png">
                                        <small>
                                            ukuran yang diterima: width 320 pixel, height 240 pixel, quality 80<br>
                                            ukuran file maksimal adalah 5MB<br>
                                            tipe file: jpeg, jpg dan png
                                        </small>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Upload Katalog atau Naskah
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="file" id="download_url" class="form-control m-input" name="download_url" placeholder="Upload Gambar Buku" accept=".pdf, .doc, .docx, .xls, .xlsx, .txt, application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, text/plain, application/pdf">
                                        <small>
                                            ukuran file maksimal adalah 10MB<br>
                                            tipe file: pdf, doc, docx, txt
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions--solid">
                                <div class="row">
                                    <div class="col-lg-2"></div>
                                    <div class="col-lg-6">
                                        <button type="submit" class="btn btn-success" id="m_sweetalert_demo_3_3">
                                            Simpan
                                        </button>
                                        <button type="reset" class="btn btn-secondary">
                                            Batal
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
</div>
@endsection

@section('scripts')
<script>
    var uploadImage = document.getElementById("image_url");

    uploadImage.onchange = function() {
        alert(this.files[0].size)
        if(this.files[0].size > 5120000) {
           alert("File is too big!");
           this.value = "";
        };
    };

    var uploadFile = document.getElementById("download_url");

    uploadFile.onchange = function() {
        alert(this.files[0].size)
        if(this.files[0].size > 10240000) {
           alert("File is too big!");
           this.value = "";
        };
    };
</script>
@endsection

resources/views/admin/catalog/edit.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-xl-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Edit Katalog
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form class="m-form" method="post" action="{{ route('admin.catalog.update', $model->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="m-portlet__body">
                            <div class="m-form__section m-form__section--first">
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Judul Katalog
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control m-input" name="title" placeholder="Masukkan Judul Katalog" value="{{ old('title', $model->title) }}" required>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Sub Judul Katalog
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control m-input" name="sub_title" placeholder="Masukkan Sub Judul Katalog" value="{{ old('sub_title', $model->sub_title) }}" required>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Upload Image
                                    </label>
                                    <div class="col-lg-6">
                                        @if ($model->image_url)
                                        <img src="{{ asset('uploads/' . $model->image_url) }}" alt="{{ $model->title }}" width="320" height="240">
                                        <input type="hidden" name="is_image" value="{{ $model->image_url }}">
                                        @endif
                                        <input type="file" class="form-control m-input" name="image_url" placeholder="Upload Gambar Katalog" accept=".jpg, .jpeg, .png, image/jpeg, image/png">
                                        <small>
                                            ukuran yang diterima: width 320 pixel, height 240 pixel, quality 80<br>
                                            tipe file: jpeg, jpg dan png
                                        </small>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Upload Katalog atau Naskah
                                    </label>
                                    <div class="col-lg-6">
                                        @if ($model->download_url)
                                        <a href="{{ asset('uploads/' . $model->download_url) }}">{{ $model->download_url }}</a>
                                        <input type="hidden" name="is_download" value="{{ $model->download_url }}">
                                        @endif
                                        <input type="file" class="form-control m-input" name="download_url" placeholder="Upload Katalog File" accept=".pdf, .doc, .docx, .xls, .xlsx, .txt, application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, text/plain, application/pdf">
                                        <small>
                                            tipe file: pdf, doc, docx, txt
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions--solid">
                                <div class="row">
                                    <div class="col-lg-2"></div>
                                    <div class="col-lg-6">
                                        <button type="submit" class="btn btn-success" id="m_sweetalert_demo_3_3">
                                            Simpan
                                        </button>
                                        <button type="reset" class="btn btn-secondary">
                                            Batal
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
</div>
@endsection

resources/views/admin/catalog/index.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Daftar Katalog
                                </h3>
                            </div>
                        </div>
                    </div>

                    <div class="m-portlet__body">
                        <!--begin::Section-->
                        <div class="m-section">
                            <div class="m-section__content">
                                @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert"></button> 
                                    <strong>{{ $message }}</strong>
                                </div>
                                @endif
                                @if ($message = Session::get('error'))
                                <div class="alert alert-danger alert-block">
                                    <button type="button" class="close" data-dismiss="alert"></button> 
                                    <strong>{{ $message }}</strong>
                                </div>
                                @endif
                                <table class="table m-table m-table--head-bg-success table-hover" style="font-size:12px;">
                                    <thead>
                                        <tr>
                                            <th>&nbsp;&nbsp;No.</th>
                                            <th>Image</th>
                                            <th>Judul Katalog</th>
                                            <th>Sub Judul Katalog</th>
                                            <th>Download</th>
                                            <th>Edit</th>
                                            <th>Hapus</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php $inc = 1 @endphp
                                        @foreach ($model as $row)
                                        <tr>
                                            <td scope="row">
                                                &nbsp;&nbsp;&nbsp;&nbsp;{{ sprintf('%03d', $inc) }}
                                            </td>
                                            <td>
                                                <img src="{{ asset('uploads/' . $row->image_url) }}" alt="{{ $row->title }}" width="22" height="32">
                                            </td>
                                            <td>{{ $row->title }}</td>
                                            <td>{{ $row->sub_title }}</td>
                                            <td>{{ $row->download_url }}</td>
                                            <td align="center">
                                                <a href="{{ route('admin.catalog.edit', $row->id) }}">
                                                    <span> <i class="fa flaticon-edit-1"></i> <span>
                                                </a>
                                            </td>
                                            <td align="center">
                                                <a href="javascript:;" data-id="{{ $row->id }}" class="remove">
                                                    <span> <i class="fa flaticon-delete-2"></i> </span>
                                                </a>
                                            </td>
                                        </tr>
                                            @php $inc++ @endphp
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!--end::Section-->
                    </div>
                </div>
                <!--end::Portlet-->
            </div>
            <!--End::Section-->
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $('.table').DataTable({
        dom: 'Bfrtip',
    });

    $(document).on('click', '.remove', function (e) {
        e.preventDefault()

        if (confirm('Apakah kamu yakin akan menghapus data ini?') == true) {
            const id = $(this).data('id')
            
            $.ajax({
                method: 'delete',
                url: '{{ route('admin.catalog.destroy', $row->id) }}',
                data: {
                    _token: '{{ csrf_token() }}',
                    id: id
                },
                cache: false,
                success: function (result) {
                    if (result.success == true) {
                        location.href = '{{ route('admin.catalog.index') }}'
                    }
                }
            })
        }
    })
</script>
@endsection