routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('home', 'HomeController@index')->name('home');
Route::get('phpinfo', function () {
    phpinfo();
});

Auth::routes();

Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Route::get('/{link}', 'HomeController@detail');
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('category', 'CategoryController');
    Route::get('book/select', 'BookController@select');
    Route::resource('book', 'BookController');
    Route::get('order/member', 'OrderController@member')->name('order.member');
    Route::put('order/status', 'OrderController@status')->name('order.status');
    Route::get('order/summary', 'OrderController@summary')->name('order.summary');
    Route::resource('order', 'OrderController');
    Route::resource('catalog', 'CatalogController');
    Route::resource('ads', 'AdsController');
    Route::resource('event', 'EventController');
    Route::resource('news', 'NewsController');
    Route::resource('promo', 'PromoController');
    Route::resource('author', 'AuthorController');
    Route::resource('slider', 'SliderController');
    Route::resource('report', 'ReportController');
    Route::get('member/order', 'MemberController@transactions')->name('member.order');
    Route::resource('member', 'MemberController');
    Route::resource('user', 'UserController');
    Route::post('logout', '\App\Http\Controllers\Auth\AdminLoginController@logout')->name('logout');
});

Route::get('admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Auth\AdminLoginController@login')->name('admin.login');
Route::get('admin/register', 'Auth\AdminLoginController@showRegisterPage')->name('admin.register');
Route::post('admin/register', 'Auth\AdminLoginController@register')->name('admin.register');

// frontend
Route::get('register', 'Auth\RegisterController@showRegisterForm')->name('register');
Route::get('member', 'HomeController@member')->name('member');
Route::post('search', 'HomeController@search')->name('search');
Route::get('get-city/{id}', 'HomeController@getCity')->name('get-city');
Route::get('get-district/{id}', 'HomeController@getDistrict')->name('get-district');
Route::get('cart', 'HomeController@cart')->name('cart');
Route::get('book/{id}', 'HomeController@book')->name('book');
Route::get('detail/{link}', 'HomeController@detail')->name('detail');
Route::get('checkout', 'HomeController@checkout')->name('checkout');
Route::post('checkout', 'HomeController@saveCheckout')->name('checkout');
Route::get('courier-check', 'HomeController@courierCheck')->name('courier-check');
Route::post('summary', 'HomeController@summary')->name('summary');
Route::get('catalog', 'HomeController@catalog')->name('catalog');
Route::get('events', 'HomeController@event')->name('events');
Route::get('event/{link}', 'HomeController@eventDetail')->name('event');
Route::get('promo/{link}', 'HomeController@promo')->name('promo');
Route::get('news-all', 'HomeController@news')->name('news-all');
Route::get('news/{link}', 'HomeController@showNews')->name('news');
Route::get('category/{link}', 'HomeController@category')->name('category');
Route::get('about-us', 'HomeController@aboutUs')->name('about-us');
Route::get('send-document', 'HomeController@sendDocument')->name('send-document');
Route::get('send-ilustrator', 'HomeController@sendIlustrator')->name('send-ilustrator');
Route::post('save-document', 'HomeController@saveDocument')->name('save-document');
Route::post('save-address', 'UserController@saveAddress')->name('save-address');
Route::post('edit-profile', 'UserController@editProfile')->name('edit-profile');
Route::get('call-us', 'HomeController@callUs')->name('call-us');
Route::post('message', 'HomeController@message')->name('message');
Route::get('wishlist', 'HomeController@wishlist')->name('wishlist');
Route::post('wishlist', 'HomeController@setWishlist')->name('wishlist');
Route::post('delete-wishlist', 'HomeController@deleteWishlist')->name('delete-wishlist');
Route::get('reseller', 'HomeController@reseller')->name('reseller');
Route::get('credit', 'HomeController@credit')->name('credit');
Route::get('testimonial', 'HomeController@testimonial')->name('testimonial');
Route::get('forgot-password', 'HomeController@forgotPassword')->name('forgot-password');
Route::post('send-forgot-password', 'HomeController@sendForgotPassword')->name('send-forgot-password');
Route::get('cara-belanja', 'HomeController@caraBelanja')->name('cara-belanja');
Route::get('pembayaran', 'HomeController@pembayaran')->name('pembayaran');
Route::get('pengiriman', 'HomeController@pengiriman')->name('pengiriman');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
        'address',
        'city',
        'region',
        'district',
        'phone',
        'zipcode',
        'sex',
        'place_of_birth',
        'date_of_birth',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function province ()
    {
        return $this->hasOne(\App\Models\Province::class, 'id', 'region');
    }

    public function cityis ()
    {
        return $this->hasOne(\App\Models\City::class, 'id', 'city');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Admin;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = Admin::get();
        
        return view('admin.user.index', compact('model'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $model = Admin::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
        ]);

        return redirect()->route('admin.user.index')->with('status', 'User berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Admin::find($id);
        
        return view('admin.user.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Admin::find($id);
        $model->name = $request->input('name');
        $model->password = Hash::make($request->input('password'));
        $model->save();

        return redirect()->route('admin.user.index')->with('success', 'User berhasil di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Admin::find($id);

        if ($model->delete())
            return response()->json([
                'success' => true,
                'message' => 'Data user berhasil dihapus',
            ]);
        else
            return response()->json([
                'success' => false,
                'message' => 'Data user tidak berhasil dihapus',
            ]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

use App\User;
use App\Models\Address;
use App\Models\Province;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth');
    }

    public function saveAddress (Request $request)
    {
        $model = Address::where('user_id', \Auth::user()->id)->first();

        if (empty($model))
            $model = new Address;
            
        $region = Province::find($request->input('region'));

        $model->user_id = \Auth::user()->id;
        $model->name = $request->input('name');
        $model->address = $request->input('address');
        $model->city_id = $request->input('city_id');
        $model->city = $request->input('city');
        $model->district_id = $request->input('district_id');
        $model->district = $request->input('district');
        $model->region = isset($region->name) ? $region->name : '';
        $model->postal_code = $request->input('postal_code');
        $model->phone = $request->input('phone');
        $model->save();

        return redirect()->route('member')->with('success', 'Alamat sudah terupdate');
    }

    public function editProfile (Request $request)
    {
        $model = User::find(\Auth::user()->id);
        $model->name = $request->input('name');

        if ($request->input('old_password') && Hash::check($request->input('old_password'), $model->password)) {
            if ($request->input('password') != $request->input('password_confirmation'))
                return redirect()->route('admin')->with('error', 'Password tidak sama');

            $model->password = Hash::make($request->input('password'));
            $model->save();
        }

        return redirect()->route('member')->with('success', 'Profile berhasil di update');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-xl-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Tambah User
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form class="m-form" method="POST" action="{{ route('admin.user.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="m-portlet__body">
                            <div class="m-form__section m-form__section--first">
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Nama User
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control m-input" name="name" placeholder="Masukkan Nama" required>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Email
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="email" class="form-control m-input" name="email" placeholder="Masukkan Email">
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Password
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="password" class="form-control m-input" name="password" placeholder="Masukkan Password">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions--solid">
                                <div class="row">
                                    <div class="col-lg-2"></div>
                                    <div class="col-lg-6">
                                        <button type="submit" class="btn btn-success" id="m_sweetalert_demo_3_3">
                                            Simpan
                                        </button>
                                        <button type="reset" class="btn btn-secondary">
                                            Batal
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-xl-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Edit User
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form class="m-form" method="post" action="{{ route('admin.user.update', $model->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="m-portlet__body">
                            <div class="m-form__section m-form__section--first">
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Nama User
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="text" class="form-control m-input" name="name" value="{{ old('name', $model->name) }}" placeholder="Masukkan Nama" required>
                                    </div>
                                </div>
                                <div class="form-group m-form__group row">
                                    <label class="col-lg-2 col-form-label">
                                        Ganti Password
                                    </label>
                                    <div class="col-lg-6">
                                        <input type="password" class="form-control m-input" name="password" placeholder="Masukkan Password baru" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions--solid">
                                <div class="row">
                                    <div class="col-lg-2"></div>
                                    <div class="col-lg-6">
                                        <button type="submit" class="btn btn-success" id="m_sweetalert_demo_3_3">
                                            Simpan
                                        </button>
                                        <button type="reset" class="btn btn-secondary">
                                            Batal
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('contents')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Daftar User
                                </h3>
                            </div>
                        </div>
                    </div>

                    <div class="m-portlet__body">
                        <!--begin::Section-->
                        <div class="m-section">
                            <div class="m-section__content">
                                @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert"></button> 
                                    <strong>{{ $message }}</strong>
                                </div>
                                @endif
                                @if ($message = Session::get('error'))
                                <div class="alert alert-danger alert-block">
                                    <button type="button" class="close" data-dismiss="alert"></button> 
                                    <strong>{{ $message }}</strong>
                                </div>
                                @endif
                                <table class="table m-table m-table--head-bg-success" style="font-size:12px;">
                                    <thead>
                                        <tr>
                                            <th>&nbsp;&nbsp;No.</th>
                                            <th>Nama</th>
                                            <th>Email</th>
                                            <th>Edit</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php $inc = 1 @endphp
                                        @foreach ($model as $row)
                                        <tr>
                                            <th scope="row">&nbsp;&nbsp;&nbsp;&nbsp;{{ sprintf('%03d', $inc) }}</th>
                                            <td>{{ $row->name }}</td>
                                            <td>{{ $row->email }}</td>
                                            <td>
                                                <a href="{{ route('admin.user.edit', $row->id) }}" class="m-btn  m-btn m-btn--icon">
                                                    <span> <i class="fa flaticon-edit-1"></i> <span>
                                                </a>
                                            </td>
                                        </tr>
                                            @php $inc++ @endphp
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!--end::Section-->
                    </div>
                </div>
                <!--end::Portlet-->
            </div>
            <!--End::Section-->
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    // $('.table').DataTable({
    //     dom: 'Bfrtip',
    // });

    $('.delete').on('click', function (e) {
        e.preventDefault();
        
        const id = $(this).data('id');
        const CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');

        Swal.fire({
            title: "Are you sure?",
            text: "Hapus User",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#033147",
            confirmButtonText: "Yes",
            cancelButtonText: "No!",
            closeOnConfirm: true,
            closeOnCancel: true
        }, function(isConfirm) {
            if (isConfirm) {
                $.ajax({
                    type: "DELETE",
                    url: "{{ url('admin/user/destroy') }}/" + id,
                    headers: {
                        'X-CSRF-TOKEN': jQuery('meta[name="csrf-token"]').attr('content')
                    },
                    data: {
                        _token: CSRF_TOKEN,
                        id : id,
                        req_id : no
                    },
                    dataType:'json',
                    success: function (data) {
                        console.log(data)
                        if( data.success == true ) {
                            swal('Success!', 'User berhasil dihapus.', 'success');   
                            location.reload();
                        } else {
                            swal('Error!','Ada yang salah', 'error');
                        }
                    },
                    error: function (data) {
                        console.log('Error:', data);
                    }
                });
            } else {     
                // swal("Cancelled", "Your imaginary file is safe :)", "error");
            }
        });
    })
</script>
@endsection